apiVersion: batch/v1
kind: CronJob
metadata:
  name: ide-test-cron
  namespace: ide
spec:
  schedule: "*/1 * * * *" # ここでスケジュールを設定。例では毎分実行。
  jobTemplate:
    spec:
      backoffLimit: 1  # Moved to jobTemplate.spec from template.spec
      template:
        spec:
          restartPolicy: Never
          containers:  # Moved to the correct level under template.spec
          - name: ide-test
            image: ubuntu
            command:
              - bash
              - -c
            args:
              - |
                echo PID=$$
                for i in {0..9}
                do
                  eval a$i'=$(head --bytes 5000000 /dev/zero |cat -v)'
                  echo $((i++));
                done
            resources:
              requests:
                memory: 100Mi
                cpu: 1
              limits:
                memory: 100Mi
                cpu: 1
